version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: group_6
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data